-- Initial schema matches the existing JPA model. No accounts or demo content.
-- Existing databases need an audited, explicit baseline at version 1.
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    role VARCHAR(255) NOT NULL CHECK (role IN ('GUEST', 'USER', 'ADMIN')),
    saves VARCHAR(255)
);

CREATE TABLE theories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL
);

CREATE TABLE theory_content (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_type VARCHAR(255) NOT NULL,
    title VARCHAR(255),
    data TEXT NOT NULL,
    media_link TEXT,
    theory_id BIGINT REFERENCES theories(id)
);

CREATE TABLE graph_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    oriented BOOLEAN NOT NULL,
    theory_content_id BIGINT REFERENCES theory_content(id)
);

CREATE TABLE graph_nodes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_id VARCHAR(255) NOT NULL,
    node_group VARCHAR(255),
    graph_data_id BIGINT REFERENCES graph_data(id)
);

CREATE TABLE graph_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    link_id VARCHAR(255),
    weight VARCHAR(255),
    source VARCHAR(255) NOT NULL,
    target VARCHAR(255) NOT NULL,
    graph_data_id BIGINT REFERENCES graph_data(id)
);

CREATE TABLE practices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL
);

CREATE TABLE practice_content (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_type VARCHAR(255) NOT NULL,
    title VARCHAR(255),
    data TEXT NOT NULL,
    media_link TEXT,
    practice_id BIGINT REFERENCES practices(id)
);

CREATE TABLE possible_vertex_counts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    count INTEGER NOT NULL,
    practice_content_id BIGINT REFERENCES practice_content(id)
);

CREATE TABLE possible_edge_counts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    count INTEGER NOT NULL,
    practice_content_id BIGINT REFERENCES practice_content(id)
);

CREATE TABLE graph_properties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property VARCHAR(255) NOT NULL CHECK (property IN (
        'CONNECTED', 'ACYCLIC', 'DIRECTED', 'WEIGHTED', 'COMPLETED', 'TREE', 'EULERIAN', 'HAMILTONIAN'
    )),
    practice_content_id BIGINT REFERENCES practice_content(id)
);

CREATE TABLE theory_completions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id),
    theory_id BIGINT REFERENCES theories(id),
    theory_title VARCHAR(255),
    theory_status VARCHAR(255) NOT NULL CHECK (theory_status IN ('COMPLETED', 'IN_PROGRESS')),
    completion_date DATE,
    CONSTRAINT uq_user_theory UNIQUE (user_id, theory_id)
);

CREATE TABLE practice_completions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id),
    practice_id BIGINT REFERENCES practices(id),
    practice_title VARCHAR(255),
    practice_status VARCHAR(255) NOT NULL CHECK (practice_status IN ('COMPLETED', 'IN_PROGRESS', 'FAILED')),
    completion_date DATE,
    CONSTRAINT uq_user_practice UNIQUE (user_id, practice_id)
);
