version: '3.8'
services:
  app:
    build:
      context: ../backend
      dockerfile: ../docker/dockerfiles/backend.Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/MTAPP
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=veryh@rdp@ss
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=MTAPP
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=veryh@rdp@ss
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
